[package]
org = "wso2"
name = "user_lifecycle_management"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "docusign.dsadmin"
version = "0.1.0"
repository = "local"
