name: Receiver Workflow (ballerina-library-test org)

on:
  repository_dispatch:
    types: [trigger-from-api-specs-test]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: |
          echo "Workflow triggered from another organization!"
          echo "Sender repo: ${{ github.event.client_payload.sender }}"
          echo "Event type: ${{ github.event.action }}"
